name = "DilatationsOfSchemes"
defaultTargets = ["DilatationsOfSchemes"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "Project"
git = "https://github.com/rndmx/MULTI-PROJ-BLOW.git"

[[lean_lib]]
name = "DilatationsOfSchemes"
globs = [
  "IdealLocality",
  "MulticenterNonZeroDivisor",
  "MulticenterTower",
  "MulticenterMonopoly",
  "MulticenterIterate",
  "MulticenterQuotient",
  "Cor240",
  "MulticenterExceptional",
  "MulticenterSingleDivisor",
  "MulticenterShift",
  "Fact51",
  "MulticenterSpanEquiv",
  "PolyptychKernel",
  "PolyptychDatum",
  "PolyptychExpand",
  "PolyptychKernelFormula",
  "PolyptychPanel",
  "PolyptychSchemeDatum",
  "PolyptychSchemeUpsilon",
  "PolyptychPanelBase",
  "PolyptychPanelChart",
  "SchemeProp317",
  "ClosMathlibBridge",
  "SchemeMultiCenterOfClosed",
  "SchemeDefSpaceSum",
  "PolyptychPanelLift",
  "PolyptychStage",
  "PanelDivisorSum",
  "PolyptychStageIdeal",
  "PolyptychUpsChart",
  "PolyptychFwd",
  "PolyptychBwd",
  "PolyptychPaperForm",
  "PolyptychRestricted",
  "CenterCover",
  "RestrictedDatum",
  "RestrictedPanelHom",
  "RestrictedChart",
  "RestrictedPanelChart",
  "RestrictedPanelCone",
  "RestrictedPanelPullback",
  "RestrictedPanelClosed",
  "RestrictedPanelIso",
  "SchemeLemma44",
  "IteratedSchemeMultiCore",
  "IteratedSchemeMultiFwd",
  "IteratedSchemeMultiBwd",
  "IteratedSchemeMulti",
  "StrictTransformPresent",
  "SchemeFact51",
  "PolyptychAssumption31",
  "TransportPrinciple",
  "Remark37",
  "SchemeMathlibForm",
  "ClosEquiv",
  "SchemeProp52",
  "DilatationCover",
  "DilatationFlatBaseChange",
  "PreClosAndClos",
  "MonoCentered",
  "DilToBlowup",
  "ProjComparison",
  "ProjReindex",
  "BlMuOpen",
  "ProjAwayIngredient",
  "ProjIsoB",
  "ProjMathlibIso",
  "ProjIsoC",
  "ReesCovering",
  "ChartBar",
  "ChartEq",
  "PartitionUnity",
  "ChartCover",
  "ProjChartRange",
  "HomogDecomp",
  "ProjSurj",
  "ReesMu",
  "ReesChartCover",
  "BlMuIso",
  "ProjIsoA",
  "ProjGlueCompat",
  "ProjOverlap",
  "PreClosClosedImmersion",
  "PreClosReindex",
  "ClosInterPullback",
  "ClosInterSch",
  "ClosSumSche",
  "InclusionClos",
  "MulticenterClos",
  "PreMultiCenter",
  "MultiCenter",
  "MultiCenterBaseChange",
  "GlobalDilatation",
  "UniversalProperty",
  "GlobalDilProperties",
  "DilatationNonZeroDivisor",
  "DilatationChart",
  "Tower",
  "IteratedDilatation",
  "SchemeMonopoly",
  "Functoriality",
  "BaseChange",
  "IteratedMultiple",
  "MultiCenterReindex",
  "Main",
]
