name = "DilatationsOfSchemes"
defaultTargets = ["DilatationsOfSchemes"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "DilatationsOfSchemes"
globs = [
  "lemma",
  "IdealLocality",
  "Family",
  "Ideal",
  "MulticenterRing",
  "MulticenterNonZeroDivisor",
  "MulticenterTower",
  "MulticenterMonopoly",
  "MulticenterIterate",
  "MulticenterQuotient",
  "MulticenterExceptional",
  "MulticenterSingleDivisor",
  "MulticenterShift",
  "MulticenterSpanEquiv",
  "PolyptychKernel",
  "PolyptychDatum",
  "PolyptychExpand",
  "PolyptychKernelFormula",
  "PolyptychPanel",
  "PolyptychSchemeDatum",
  "PolyptychSchemeUpsilon",
  "PolyptychPanelBase",
  "PolyptychPanelChart",
  "PolyptychPanelLift",
  "PolyptychStage",
  "PolyptychStageIdeal",
  "PolyptychUpsChart",
  "PolyptychFwd",
  "PolyptychBwd",
  "PolyptychPaperForm",
  "PolyptychRestricted",
  "CenterCover",
  "RestrictedDatum",
  "RestrictedPanelHom",
  "RestrictedChart",
  "RestrictedPanelChart",
  "RestrictedPanelCone",
  "RestrictedPanelPullback",
  "RestrictedPanelIso",
  "SchemeLemma44",
  "IteratedSchemeMultiCore",
  "IteratedSchemeMultiFwd",
  "IteratedSchemeMultiBwd",
  "IteratedSchemeMulti",
  "StrictTransformPresent",
  "SchemeFact51",
  "SchemeProp52",
  "DilatationCover",
  "CubeIdentity",
  "AlgEquivRestrictScalars",
  "Flat",
  "DilatationFlatBaseChange",
  "PreClosAndClos",
  "PreClosClosedImmersion",
  "PreClosReindex",
  "ClosInterPullback",
  "ClosInterSch",
  "ClosSumSche",
  "InclusionClos",
  "MulticenterClos",
  "PreMultiCenter",
  "MultiCenter",
  "MultiCenterBaseChange",
  "GlobalDilatation",
  "UniversalProperty",
  "GlobalDilProperties",
  "DilatationNonZeroDivisor",
  "DilatationChart",
  "Tower",
  "IteratedDilatation",
  "SchemeMonopoly",
  "Functoriality",
  "BaseChange",
  "IteratedMultiple",
  "MultiCenterReindex",
  "Main",
]
