import MulticenterSingleDivisor
import MulticenterMonopoly

/-!
# Shifting a multicenter by a common factor: [Ma24, Prop. 5.2] at the ring level

Section 5 of [Ma24] studies dilatations along multiples `s₀D, …, s_kD` of a *single*
divisor `D`, and Prop. 5.2 states, for `0 ≤ t ≤ s₀`, a canonical identification of
`X`-spaces

  `Bl^t_{Y₀} Bl^{s₀,…,s_k}_{Y₀,…,Y_k} X = Bl^{s₀+t,…,s_k+t}_{Y₀,…,Y_k} X`.

Its proof reduces to the affine case, where it becomes the displayed identification of
rings

  `(A[M₀/a^{s₀}, …, M_k/a^{s_k}])[Q/a^t] = A[M₀/a^{s₀+t}, …, M_k/a^{s_k+t}]`,

`Q` being the ideal of [Ma24, Fact 5.1] (`Multicenter.genFracIdeal`, proved in
`MulticenterSingleDivisor.lean` to be the kernel of the canonical map to `A/M₀`).

This file proves that identification in the following **more general form**, which needs
neither that the distinguished elements be powers of one element `a`, nor `t ≤ s₀`, nor
finiteness of the index set:

* `Multicenter.shift F c` — the multicenter `{[Mᵢ, aᵢ·c]}`, same centers, every
  distinguished element multiplied by a common `c`;
* `Multicenter.secondStage F c` — the mono-centered multicenter on `A[F]` with center the
  Fact 5.1 ideal `Q` and distinguished element the image of `c`;
* `Multicenter.shiftEquiv` — **the identification**
  `(A[F])[Q/c] ≃ₐ[A] A[F.shift c]`, together with `shiftEquiv_unique`.

Both directions come from the universal property, following the template of
`Multicenter.iterateEquiv` (`MulticenterIterate.lean`, the ring level of Lemma 4.4):

* `toShift` is the comparison `A[F] →ₐ[A] A[F.shift c]` — its non-zero-divisor condition
  holds because `aᵢ·c` is a non-zero-divisor downstairs, hence so is its factor `aᵢ`;
* `toShift_frac` is the key computation `τ(m/aᵢ) = c · (m/(aᵢ·c))`, obtained from
  `dsc_spec` by cancelling the non-zero-divisor `aᵢ`; it is what makes the Fact 5.1 ideal
  land inside the principal ideal generated by `c`, giving the span condition for `Φ`;
* conversely `m = aᵢ · (m/aᵢ)` in `A[F]` with `m/aᵢ ∈ Q ⊆ (c)`, which gives the span
  condition for `Ψ`.

The two composites are identities by `lemma_exists_unique_morphism'`, the `A[F]`-algebra
structure on `A[F.shift c]` being installed from `τ` exactly as in `iterateEquiv`.
-/

suppress_compilation

universe u

open Family

namespace Multicenter

section Prop52

variable {A : Type (u+1)} [CommRing A] (F : Multicenter A) (c : A)

open Dilatation

/-- **Shifting a multicenter by a common factor**: same centers, every distinguished
element multiplied by `c`.  For `F.elem i = a^{sᵢ}` and `c = a^t` this is the multicenter
`{[Mᵢ, a^{sᵢ+t}]}` of [Ma24, Prop. 5.2]. -/
def shift : Multicenter A where
  index := F.index
  ideal := F.ideal
  elem i := F.elem i * c

@[simp] lemma shift_ideal (i : F.index) : (F.shift c).ideal i = F.ideal i := rfl

@[simp] lemma shift_elem (i : F.index) : (F.shift c).elem i = F.elem i * c := rfl

/-- In `A[F.shift c]` the image of each `F.elem i` is a non-zero-divisor. -/
lemma shift_elem_nzd (i : F.index) :
    algebraMap A A[F.shift c] (F.elem i) ∈ nonZeroDivisors A[F.shift c] := by
  have h := nonzerodiv_image_single (F.shift c) i
  rw [shift_elem, map_mul] at h
  exact (mul_mem_nonZeroDivisors.mp h).1

/-- In `A[F.shift c]` the image of `c` is a non-zero-divisor (given some index). -/
lemma shift_c_nzd (i₀ : F.index) :
    algebraMap A A[F.shift c] c ∈ nonZeroDivisors A[F.shift c] := by
  have h := nonzerodiv_image_single (F.shift c) i₀
  rw [shift_elem, map_mul] at h
  exact (mul_mem_nonZeroDivisors.mp h).2

/-- The span condition for the comparison `A[F] → A[F.shift c]`. -/
lemma toShift_gen : ∀ i, Ideal.span {algebraMap A A[F.shift c] (F.elem i)} =
    Ideal.map (algebraMap A A[F.shift c]) (F.LargeIdeal i) := by
  intro i
  refine (gen_iff_le F i).mpr ?_
  refine le_trans (Multicenter.self_le (F.shift c) i) ?_
  rw [shift_elem, map_mul]
  exact Ideal.span_singleton_le_span_singleton.mpr
    ⟨algebraMap A A[F.shift c] c, rfl⟩

/-- **The comparison `τ : A[F] →ₐ[A] A[F.shift c]`.** -/
def toShift : A[F] →ₐ[A] A[F.shift c] :=
  desc F (F.shift_elem_nzd c) (F.toShift_gen c)

/-- **The key computation**: `τ` sends the generator `m/aᵢ` of the Fact 5.1 ideal to
`c · (m/(aᵢc))`.  So the whole ideal lands in the principal ideal generated by `c`. -/
lemma toShift_frac (i : F.index) {m : A} (hm : m ∈ F.ideal i) :
    F.toShift c (Dilatation.frac (F := F) (Finsupp.single i 1)
        ⟨m, F.mem_largeIdealPow_single i hm⟩) =
      algebraMap A A[F.shift c] c *
        Dilatation.frac (F := F.shift c) (Finsupp.single i 1)
          ⟨m, (F.shift c).mem_largeIdealPow_single i hm⟩ := by
  have h1 := dsc_spec F (Finsupp.single i 1)
    ⟨m, F.mem_largeIdealPow_single i hm⟩ (F.shift_elem_nzd c) (F.toShift_gen c)
  rw [familyPow_single] at h1
  have h2 := (F.shift c).algebraMap_eq_pow_mul_frac (Finsupp.single i 1) m
    ((F.shift c).mem_largeIdealPow_single i hm)
  rw [familyPow_single, shift_elem, map_mul] at h2
  have hzero : algebraMap A A[F.shift c] (F.elem i) *
      (F.toShift c (Dilatation.frac (F := F) (Finsupp.single i 1)
          ⟨m, F.mem_largeIdealPow_single i hm⟩) -
        algebraMap A A[F.shift c] c *
          Dilatation.frac (F := F.shift c) (Finsupp.single i 1)
            ⟨m, (F.shift c).mem_largeIdealPow_single i hm⟩) = 0 := by
    rw [mul_sub, show algebraMap A A[F.shift c] (F.elem i) *
      F.toShift c (Dilatation.frac (F := F) (Finsupp.single i 1)
        ⟨m, F.mem_largeIdealPow_single i hm⟩) =
      algebraMap A A[F.shift c] m from h1]
    rw [h2]
    ring
  exact sub_eq_zero.mp
    ((mul_left_mem_nonZeroDivisors_eq_zero_iff (F.shift_elem_nzd c i)).mp hzero)

/-- An eliminator for the Fact 5.1 ideal. -/
lemma genFracIdeal_le {J : Ideal A[F]}
    (h : ∀ (i : F.index) (m : A) (hm : m ∈ F.ideal i),
      Dilatation.frac (F := F) (Finsupp.single i 1)
        ⟨m, F.mem_largeIdealPow_single i hm⟩ ∈ J) :
    F.genFracIdeal ≤ J := by
  refine iSup_le fun i => ?_
  rw [Ideal.span_le]
  rintro x ⟨m, hm, rfl⟩
  exact h i m hm

/-- **The second-stage (mono-centered) multicenter on `A[F]`**: the center is the
Fact 5.1 ideal `Q = ⟨Mᵢ/aᵢ⟩`, the distinguished element is the image of `c`. -/
def secondStage : Multicenter A[F] where
  index := PUnit
  ideal _ := F.genFracIdeal
  elem _ := algebraMap A A[F] c

@[simp] lemma secondStage_ideal (u : PUnit) :
    (F.secondStage c).ideal u = F.genFracIdeal := rfl

@[simp] lemma secondStage_elem (u : PUnit) :
    (F.secondStage c).elem u = algebraMap A A[F] c := rfl

/-- The `A[F]`-algebra structure on `A[F.shift c]` given by `τ`. -/
local instance shiftAlgebra : Algebra A[F] A[F.shift c] :=
  (F.toShift c).toRingHom.toAlgebra

local instance : IsScalarTower A A[F] A[F.shift c] :=
  IsScalarTower.of_algebraMap_eq fun a => ((F.toShift c).commutes a).symm

local instance : IsScalarTower A A[F] ((A[F])[F.secondStage c]) :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

/-- Non-zero-divisor condition for the map out of the two-stage ring. -/
lemma fromSecondStage_nzd (i₀ : F.index) :
    ∀ u : PUnit, (F.toShift c) ((F.secondStage c).elem u) ∈
      nonZeroDivisors A[F.shift c] := by
  intro u
  rw [secondStage_elem, (F.toShift c).commutes]
  exact F.shift_c_nzd c i₀

/-- Span condition for the map out of the two-stage ring: the Fact 5.1 ideal maps into
the principal ideal generated by `c`. -/
lemma fromSecondStage_gen :
    ∀ u : PUnit, Ideal.map (F.toShift c).toRingHom ((F.secondStage c).ideal u) ≤
      Ideal.span {(F.toShift c) ((F.secondStage c).elem u)} := by
  intro u
  rw [secondStage_ideal, secondStage_elem, (F.toShift c).commutes,
    Ideal.map_le_iff_le_comap]
  refine F.genFracIdeal_le (fun i m hm => ?_)
  rw [Ideal.mem_comap]
  show F.toShift c (Dilatation.frac (F := F) (Finsupp.single i 1)
      ⟨m, F.mem_largeIdealPow_single i hm⟩) ∈ _
  rw [F.toShift_frac c i hm]
  exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)

/-- **`Φ`**: the two-stage dilatation maps to the shifted one-stage dilatation. -/
def fromSecondStage (i₀ : F.index) :
    (A[F])[F.secondStage c] →ₐ[A[F]] A[F.shift c] :=
  desc (F.secondStage c) (F.fromSecondStage_nzd c i₀)
    (fun u => (gen_iff_le (F.secondStage c) u).mpr (F.fromSecondStage_gen c u))

/-- In the two-stage ring, the image of `F.elem i` is a non-zero-divisor. -/
lemma twoStage_elem_nzd (i : F.index) :
    algebraMap A ((A[F])[F.secondStage c]) (F.elem i) ∈
      nonZeroDivisors ((A[F])[F.secondStage c]) :=
  Dilatation.nonzerodiv_of_nonzerodiv (F := F.secondStage c)
    (nonzerodiv_image_single F i)

/-- In the two-stage ring, the image of `c` is a non-zero-divisor. -/
lemma twoStage_c_nzd :
    algebraMap A ((A[F])[F.secondStage c]) c ∈
      nonZeroDivisors ((A[F])[F.secondStage c]) :=
  nonzerodiv_image_single (F.secondStage c) PUnit.unit

/-- Non-zero-divisor condition for the map into the two-stage ring. -/
lemma toSecondStage_nzd :
    ∀ i, algebraMap A ((A[F])[F.secondStage c]) ((F.shift c).elem i) ∈
      nonZeroDivisors ((A[F])[F.secondStage c]) := by
  intro i
  rw [shift_elem, map_mul]
  exact mul_mem (F.twoStage_elem_nzd c i) (F.twoStage_c_nzd c)

/-- Span condition for the map into the two-stage ring. -/
lemma toSecondStage_gen :
    ∀ i, Ideal.span {algebraMap A ((A[F])[F.secondStage c]) ((F.shift c).elem i)} =
      Ideal.map (algebraMap A ((A[F])[F.secondStage c])) ((F.shift c).LargeIdeal i) := by
  intro i
  refine (gen_iff_le (F.shift c) i).mpr ?_
  rw [Ideal.map_le_iff_le_comap]
  intro m hm
  rw [Ideal.mem_comap, shift_elem, map_mul]
  -- in `A[F]`, `m = aᵢ · (m/aᵢ)`, and `m/aᵢ ∈ Q` maps into `span {c}`
  have hA := F.algebraMap_eq_pow_mul_frac (Finsupp.single i 1) m
    (F.mem_largeIdealPow_single i hm)
  rw [familyPow_single] at hA
  have hQ : algebraMap A[F] ((A[F])[F.secondStage c])
      (Dilatation.frac (F := F) (Finsupp.single i 1)
        ⟨m, F.mem_largeIdealPow_single i hm⟩) ∈
      Ideal.span {algebraMap A[F] ((A[F])[F.secondStage c])
        ((F.secondStage c).elem PUnit.unit)} :=
    Multicenter.self_le (F.secondStage c) PUnit.unit
      (Ideal.mem_map_of_mem _ (F.frac_mem_genFracIdeal i hm))
  rw [secondStage_elem] at hQ
  obtain ⟨z, hz⟩ := Ideal.mem_span_singleton'.mp hQ
  refine Ideal.mem_span_singleton'.mpr ⟨z, ?_⟩
  have hpush : algebraMap A ((A[F])[F.secondStage c]) m =
      algebraMap A ((A[F])[F.secondStage c]) (F.elem i) *
        algebraMap A[F] ((A[F])[F.secondStage c])
          (Dilatation.frac (F := F) (Finsupp.single i 1)
            ⟨m, F.mem_largeIdealPow_single i hm⟩) := by
    show algebraMap A[F] ((A[F])[F.secondStage c])
        (algebraMap A A[F] m) = _
    rw [hA, map_mul]
    rfl
  rw [hpush, ← hz,
    show algebraMap A[F] ((A[F])[F.secondStage c]) (algebraMap A A[F] c) =
      algebraMap A ((A[F])[F.secondStage c]) c from rfl]
  ring

/-- **`Ψ`**: the shifted one-stage dilatation maps to the two-stage dilatation. -/
def toSecondStage : A[F.shift c] →ₐ[A] (A[F])[F.secondStage c] :=
  desc (F.shift c) (F.toSecondStage_nzd c) (F.toSecondStage_gen c)

/-- `Psi` restricted along `tau` is the canonical inclusion into the two-stage ring. -/
lemma toSecondStage_comp_toShift :
    (F.toSecondStage c).comp (F.toShift c) =
      IsScalarTower.toAlgHom A A[F] ((A[F])[F.secondStage c]) := by
  refine lemma_exists_unique_morphism' F (fun i => ?_) (fun i => ?_) _ _
  · exact F.twoStage_elem_nzd c i
  · refine (gen_iff_le F i).mpr ?_
    have hpush : Ideal.map (algebraMap A[F] ((A[F])[F.secondStage c]))
        (Ideal.map (algebraMap A A[F]) (F.ideal i)) <=
        Ideal.map (algebraMap A[F] ((A[F])[F.secondStage c]))
          (Ideal.span {algebraMap A A[F] (F.elem i)}) :=
      Ideal.map_mono (Multicenter.self_le F i)
    rw [Ideal.map_map, Ideal.map_span, Set.image_singleton] at hpush
    exact hpush

/-- `Psi` as a map of `A[F]`-algebras. -/
def toSecondStageB :
    A[F.shift c] →ₐ[A[F]] (A[F])[F.secondStage c] where
  toRingHom := (F.toSecondStage c).toRingHom
  commutes' b := by
    have h := DFunLike.congr_fun (F.toSecondStage_comp_toShift c) b
    simpa using h

/-- Round trip on the two-stage ring. -/
lemma toSecondStageB_comp_fromSecondStage (i0 : F.index) :
    (F.toSecondStageB c).comp (F.fromSecondStage c i0) =
      AlgHom.id A[F] ((A[F])[F.secondStage c]) :=
  lemma_exists_unique_morphism' (F.secondStage c)
    (fun u => nonzerodiv_image_single (F.secondStage c) u)
    (fun u => reciprocal_for_univ (F.secondStage c)
      (AlgHom.id A[F] ((A[F])[F.secondStage c])) u) _ _

/-- Round trip on the shifted one-stage ring. -/
lemma fromSecondStage_comp_toSecondStage (i0 : F.index) :
    ((F.fromSecondStage c i0).restrictScalars A).comp (F.toSecondStage c) =
      AlgHom.id A A[F.shift c] :=
  lemma_exists_unique_morphism' (F.shift c)
    (fun i => nonzerodiv_image_single (F.shift c) i)
    (fun i => reciprocal_for_univ (F.shift c) (AlgHom.id A A[F.shift c]) i) _ _

/-- **[Ma24, Prop. 5.2], ring level**: dilating `A[F]` along the Fact 5.1 ideal
`Q` with distinguished element `c` gives the dilatation of `A` along the shifted
multicenter, `(A[{Mi/ai}])[Q/c] = A[{Mi/(ai*c)}]` as `A`-algebras.  With
`ai = a^{si}` and `c = a^t` this is the displayed identification of rings in the
proof of [Ma24, Prop. 5.2]. -/
def shiftEquiv (i0 : F.index) :
    (A[F])[F.secondStage c] ≃ₐ[A] A[F.shift c] :=
  AlgEquiv.ofAlgHom ((F.fromSecondStage c i0).restrictScalars A)
    (F.toSecondStage c)
    (F.fromSecondStage_comp_toSecondStage c i0)
    (AlgHom.ext fun x =>
      DFunLike.congr_fun (F.toSecondStageB_comp_fromSecondStage c i0) x)

/-- The identification of [Ma24, Prop. 5.2] is the unique `A`-algebra map. -/
lemma shiftEquiv_unique (i0 : F.index)
    (chi : (A[F])[F.secondStage c] →ₐ[A] A[F.shift c]) :
    chi = ((F.fromSecondStage c i0).restrictScalars A) := by
  have h1 : chi.comp (IsScalarTower.toAlgHom A A[F]
      ((A[F])[F.secondStage c])) = F.toShift c := by
    refine lemma_exists_unique_morphism' F (fun i => ?_) (fun i => ?_) _ _
    · exact F.shift_elem_nzd c i
    · exact F.toShift_gen c i
  let chiB : (A[F])[F.secondStage c] →ₐ[A[F]] A[F.shift c] :=
    AlgHom.mk chi.toRingHom (fun b => by
      have h := DFunLike.congr_fun h1 b
      simpa using h)
  have h2 : chiB = F.fromSecondStage c i0 :=
    lemma_exists_unique_morphism' (F.secondStage c)
      (F.fromSecondStage_nzd c i0)
      (fun u => (gen_iff_le (F.secondStage c) u).mpr
        (F.fromSecondStage_gen c u)) _ _
  exact AlgHom.ext fun x => DFunLike.congr_fun h2 x

section Powers

variable {A : Type (u+1)} [CommRing A]

/-- The multicenter of [Ma24, §5]: a single divisor `D = Spec(A/(a))` taken with
multiplicities `sᵢ`, and centers `Yᵢ = Spec(A/Mᵢ)`. -/
def ofPowers {ι : Type} (M : ι → Ideal A) (a : A) (s : ι → ℕ) : Multicenter A where
  index := ι
  ideal := M
  elem i := a ^ s i

@[simp] lemma ofPowers_ideal {ι : Type} (M : ι → Ideal A) (a : A) (s : ι → ℕ)
    (i : ι) : (ofPowers M a s).ideal i = M i := rfl

@[simp] lemma ofPowers_elem {ι : Type} (M : ι → Ideal A) (a : A) (s : ι → ℕ)
    (i : ι) : (ofPowers M a s).elem i = a ^ s i := rfl

/-- Shifting by `a^t` raises every multiplicity by `t`. -/
theorem ofPowers_shift {ι : Type} (M : ι → Ideal A) (a : A) (s : ι → ℕ) (t : ℕ) :
    (ofPowers M a s).shift (a ^ t) = ofPowers M a (fun i => s i + t) := by
  show Multicenter.mk ι M (fun i => a ^ s i * a ^ t) =
    Multicenter.mk ι M (fun i => a ^ (s i + t))
  congr 1
  exact funext fun i => (pow_add a (s i) t).symm

/-- **[Ma24, Prop. 5.2], ring level, in the paper's notation**: for a single divisor
`(a)`, centers `Mᵢ` and multiplicities `sᵢ`, dilating along the Fact 5.1 ideal `Q` with
element `a^t` raises every multiplicity by `t`:

  `(A[{Mᵢ/a^{sᵢ}}])[Q/a^t] ≃ₐ[A] A[{Mᵢ/a^{sᵢ+t}}]`. -/
def powersShiftEquiv {ι : Type} (M : ι → Ideal A) (a : A) (s : ι → ℕ) (t : ℕ)
    (i₀ : ι) :
    (A[ofPowers M a s])[(ofPowers M a s).secondStage (a ^ t)] ≃ₐ[A]
      A[ofPowers M a (fun i => s i + t)] := by
  rw [← ofPowers_shift M a s t]
  exact (ofPowers M a s).shiftEquiv (a ^ t) i₀

end Powers

end Prop52

end Multicenter
