import PolyptychDatum

/-!
# Expansion of the large-ideal power, and the fraction pullback

Two auxiliary tools for the proof of the kernel formula (`prop:Kernel-formula`) of
Dubouloz-Mayeux, *A polyptych of multi-centered deformation spaces*.

* `largeIdealPow_le_expIdeal` expands `L^ν = ∏ (Mⱼ + (aⱼ))^{νⱼ}` into the sum, over all
  splittings `α + β = ν`, of the ideals `(∏ Mⱼ^{αⱼ}) · (a^β)`.

* `fracPullback ν P` is the ideal of numerators `ℓ ∈ L^ν` whose fraction `ℓ/a^ν` lies in a
  given ideal `P` of the dilatation.  It converts statements about ideals of `A[F]` into
  statements about ideals of `A`, where the hypotheses `(R₁)`, `(R₂)` live.
-/

suppress_compilation

universe u

open Family Multicenter Dilatation

namespace Multicenter

variable {A : Type (u+1)} [CommRing A] (F : Multicenter A)

section Expansion

/-- The set of elementary products `a · a^β` with `a ∈ ∏ Mⱼ^{αⱼ}` and `α + β = ν`. -/
def expSet (ν : F.index →₀ ℕ) : Set A :=
  {x : A | ∃ (α β : F.index →₀ ℕ) (a : A),
    α + β = ν ∧ a ∈ F.ideal ^ α ∧ x = a * F.elem ^ β}

lemma mem_expSet (ν α β : F.index →₀ ℕ) (a : A) (hαβ : α + β = ν)
    (ha : a ∈ F.ideal ^ α) : a * F.elem ^ β ∈ F.expSet ν :=
  ⟨α, β, a, hαβ, ha, rfl⟩

/-- **Expansion of the large-ideal power**: `∏ (Mⱼ + (aⱼ))^{νⱼ}` is contained in the ideal
generated by the products `(∏ Mⱼ^{αⱼ}) · a^β` over the splittings `α + β = ν`. -/
theorem largeIdealPow_le_span_expSet (ν : F.index →₀ ℕ) :
    F.LargeIdeal ^ ν ≤ Ideal.span (F.expSet ν) := by
  classical
  induction hn : _root_.finsuppDeg ν using Nat.strong_induction_on generalizing ν with
  | _ n ih =>
    subst hn
    rcases eq_or_ne ν 0 with rfl | hν
    · intro x _
      have h1 : (1 : A) ∈ F.expSet 0 := by
        refine ⟨0, 0, 1, by simp, by simp, by simp⟩
      have : Ideal.span (F.expSet 0) = ⊤ :=
        Ideal.eq_top_iff_one _ |>.mpr (Ideal.subset_span h1)
      rw [this]; trivial
    · obtain ⟨j, ν', rfl⟩ := _root_.exists_single_add_of_ne_zero ν hν
      have hdeg : _root_.finsuppDeg ν' <
          _root_.finsuppDeg (Finsupp.single j 1 + ν') := by
        rw [_root_.finsuppDeg_single_add]; omega
      have IH := ih _ hdeg ν' rfl
      have hsplit : F.LargeIdeal ^ (Finsupp.single j 1 + ν') =
          F.LargeIdeal j * F.LargeIdeal ^ ν' := by
        rw [familyPow_add, familyPow_single]
      rw [hsplit]
      refine le_trans (Ideal.mul_mono le_rfl IH) ?_
      refine Ideal.mul_le.2 fun r hr s hs => ?_
      -- `r ∈ Mⱼ + (aⱼ)`
      rw [LargeIdeal, Submodule.add_eq_sup, Submodule.mem_sup] at hr
      obtain ⟨m, hm, t, ht, rfl⟩ := hr
      obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp ht
      rw [add_mul]
      refine Ideal.add_mem _ ?_ ?_
      · -- the `Mⱼ`-branch
        refine Submodule.span_induction (p := fun y _ => m * y ∈ Ideal.span (F.expSet
            (Finsupp.single j 1 + ν'))) ?_ (by simp) ?_ ?_ hs
        · rintro y ⟨α, β, a, hαβ, ha, rfl⟩
          have hmem : m * a * F.elem ^ β ∈ F.expSet (Finsupp.single j 1 + ν') := by
            refine F.mem_expSet _ (Finsupp.single j 1 + α) β (m * a) ?_ ?_
            · rw [← hαβ]; abel
            · rw [familyPow_add, familyPow_single]
              exact Ideal.mul_mem_mul hm ha
          rw [show m * (a * F.elem ^ β) = m * a * F.elem ^ β from (mul_assoc _ _ _).symm]
          exact Ideal.subset_span hmem
        · intro y z _ _ hy hz
          rw [mul_add]; exact Ideal.add_mem _ hy hz
        · intro e y _ hy
          rw [smul_eq_mul, show m * (e * y) = e * (m * y) by ring]
          exact Ideal.mul_mem_left _ _ hy
      · -- the `(aⱼ)`-branch
        refine Submodule.span_induction (p := fun y _ => c * F.elem j * y ∈
            Ideal.span (F.expSet (Finsupp.single j 1 + ν'))) ?_ (by simp) ?_ ?_ hs
        · rintro y ⟨α, β, a, hαβ, ha, rfl⟩
          have hmem : a * F.elem ^ (Finsupp.single j 1 + β) ∈
              F.expSet (Finsupp.single j 1 + ν') :=
            F.mem_expSet _ α (Finsupp.single j 1 + β) a (by rw [← hαβ]; abel) ha
          have : c * F.elem j * (a * F.elem ^ β) =
              c * (a * F.elem ^ (Finsupp.single j 1 + β)) := by
            rw [familyPow_add, familyPow_single]; ring
          rw [this]
          exact Ideal.mul_mem_left _ _ (Ideal.subset_span hmem)
        · intro y z _ _ hy hz
          rw [mul_add]; exact Ideal.add_mem _ hy hz
        · intro e y _ hy
          rw [smul_eq_mul, ← mul_assoc, mul_comm (c * F.elem j) e, mul_assoc]
          exact Ideal.mul_mem_left _ _ hy

end Expansion

section FracPullback

/-- The ideal of numerators: `ℓ ∈ L^ν` such that the fraction `ℓ/a^ν` lies in `P`. -/
def fracPullback (ν : F.index →₀ ℕ) (P : Ideal A[F]) : Ideal A where
  carrier := {ℓ : A | ∃ h : ℓ ∈ F.LargeIdeal ^ ν, Dilatation.frac ν ⟨ℓ, h⟩ ∈ P}
  add_mem' := by
    rintro x y ⟨hx, hxP⟩ ⟨hy, hyP⟩
    refine ⟨Submodule.add_mem _ hx hy, ?_⟩
    rw [F.frac_add_same ν x y hx hy]
    exact Ideal.add_mem _ hxP hyP
  zero_mem' := ⟨Submodule.zero_mem _, by
    have : Dilatation.frac (F := F) ν ⟨0, Submodule.zero_mem _⟩ = 0 := by
      simp only [Dilatation.frac, Dilatation.zero_def, Dilatation.mk_eq_mk]
      exact ⟨0, by simp⟩
    rw [this]; exact Submodule.zero_mem _⟩
  smul_mem' := by
    rintro c x ⟨hx, hxP⟩
    refine ⟨Submodule.smul_mem _ _ hx, ?_⟩
    show Dilatation.frac (F := F) ν ⟨c * x, Ideal.mul_mem_left _ c hx⟩ ∈ P
    rw [← F.algebraMap_mul_frac c ν x hx]
    exact Ideal.mul_mem_left _ _ hxP

lemma mem_fracPullback {ν : F.index →₀ ℕ} {P : Ideal A[F]} {ℓ : A} :
    ℓ ∈ F.fracPullback ν P ↔
      ∃ h : ℓ ∈ F.LargeIdeal ^ ν, Dilatation.frac ν ⟨ℓ, h⟩ ∈ P := Iff.rfl

lemma frac_mem_of_mem_fracPullback {ν : F.index →₀ ℕ} {P : Ideal A[F]} {ℓ : A}
    (h : ℓ ∈ F.LargeIdeal ^ ν) (hℓ : ℓ ∈ F.fracPullback ν P) :
    Dilatation.frac ν ⟨ℓ, h⟩ ∈ P := by
  obtain ⟨h', hP⟩ := hℓ
  exact hP

end FracPullback

section FracLemmas

/-- A fraction whose numerator is divisible by the full denominator is an algebra image. -/
lemma frac_pow_mul (ν : F.index →₀ ℕ) (m : A)
    (h : m * F.elem ^ ν ∈ F.LargeIdeal ^ ν) :
    Dilatation.frac ν ⟨m * F.elem ^ ν, h⟩ = algebraMap A A[F] m := by
  simp only [Dilatation.frac, Dilatation.algebraMap_apply, Dilatation.mk_eq_mk]
  exact ⟨0, by simp [familyPow_add]⟩

/-- Multiplicativity of fractions, in the direction used below. -/
lemma frac_mul (v w : F.index →₀ ℕ) (x y : A) (hx : x ∈ F.LargeIdeal ^ v)
    (hy : y ∈ F.LargeIdeal ^ w) (hxy : x * y ∈ F.LargeIdeal ^ (v + w)) :
    Dilatation.frac (v + w) ⟨x * y, hxy⟩ =
      Dilatation.frac v ⟨x, hx⟩ * Dilatation.frac w ⟨y, hy⟩ := by
  rw [Dilatation.frac_mul_frac]

/-- Elements of `(a) · N` are exactly the `a · q` with `q ∈ N`. -/
lemma mem_span_singleton_mul_iff {a : A} {N : Ideal A} {t : A} :
    t ∈ Ideal.span {a} * N ↔ ∃ q ∈ N, t = a * q := by
  constructor
  · intro ht
    refine Submodule.mul_induction_on ht ?_ ?_
    · rintro x hx y hy
      obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hx
      exact ⟨c * y, Ideal.mul_mem_left _ _ hy, by ring⟩
    · rintro x y ⟨q, hq, rfl⟩ ⟨q', hq', rfl⟩
      exact ⟨q + q', Ideal.add_mem _ hq hq', by ring⟩
  · rintro ⟨q, hq, rfl⟩
    exact Ideal.mul_mem_mul (Ideal.mem_span_singleton_self a) hq

end FracLemmas

end Multicenter
