import MulticenterTower
import MulticenterMonopoly
import MulticenterNonZeroDivisor
import MulticenterIterate
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The kernel of a quotient dilatation morphism

This file formalizes Proposition `propnoyauappendix` of Dubouloz–Mayeux, *A polyptych of
multi-centered deformation spaces* (arXiv:2411.15606), a variant of [Ma24, Prop. 2.39].

Let `A` be a ring, `F = {(Mᵢ, aᵢ)}ᵢ` a multicenter on `A` and `T ⊆ A` an ideal.  Reducing
`F` modulo `T` gives a multicenter `F.quotCenter T` on `A ⧸ T`, and the two dilatation
homomorphisms fit in a commutative square

```
  (A⧸T)[{(Mᵢ+T)/π(aᵢ)}]  ←τ*—  A⧸T
        ↑ φ                      ↑ π
      A[{Mᵢ/aᵢ}]         ←σ*—    A
```

**Main result** (`ker_quotHom`).  If `π(aᵢ)` is a non-zero-divisor in `A ⧸ T` for every `i`,
then
`ker φ = Σ_ν (Lᵛ ∩ T)/aᵛ`,
the ideal generated by all fractions `ℓ/aᵛ` whose numerator lies in `T`.

The proof is the one in the paper: `τ*` is injective because the `π(aᵢ)` are
non-zero-divisors (`algebraMap_injective_of_elem_nzd`, [Ma24, Prop. 2.20]), and
`φ(σ*(ℓ)) = ψ(ℓ)` where `ψ = τ* ∘ π`, so `φ(ℓ/aᵛ) = 0 ↔ ψ(ℓ) = 0 ↔ π(ℓ) = 0 ↔ ℓ ∈ T`,
the middle step using that `ψ(aᵛ) = φ(σ*(aᵛ))` is a non-zero-divisor.
-/

suppress_compilation

universe u

open Family Multicenter Dilatation

section IdealProd

/-- `Ideal.map` commutes with finite products of ideals. -/
theorem Ideal.map_finset_prod {A B : Type*} [CommRing A] [CommRing B] (f : A →+* B)
    {ι : Type*} (S : Finset ι) (I : ι → Ideal A) :
    Ideal.map f (∏ s ∈ S, I s) = ∏ s ∈ S, Ideal.map f (I s) := by
  classical
  induction S using Finset.induction with
  | empty =>
    simp only [Finset.prod_empty, Ideal.one_eq_top]
    exact Ideal.map_top f
  | insert a S ha ih =>
    rw [Finset.prod_insert ha, Finset.prod_insert ha, Ideal.map_mul, ih]

end IdealProd

namespace Multicenter

section injective

variable {R : Type (u+1)} [CommRing R] (G : Multicenter R)

/-- A family power of non-zero-divisors is a non-zero-divisor. -/
lemma familyPow_mem_nonZeroDivisors (h : ∀ i, G.elem i ∈ nonZeroDivisors R)
    (β : G.index →₀ ℕ) : G.elem ^ β ∈ nonZeroDivisors R := by
  classical
  simp only [familyPow_def, Finsupp.prod]
  exact prod_mem fun i _ => pow_mem (h i) _

/-- **[Ma24, Prop. 2.20]**: if all the distinguished elements of a multicenter are
non-zero-divisors, the dilatation homomorphism `R → R[G]` is injective. -/
theorem algebraMap_injective_of_elem_nzd (h : ∀ i, G.elem i ∈ nonZeroDivisors R) :
    Function.Injective (algebraMap R R[G]) := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  rw [algebraMap_apply, zero_def, mk_eq_mk] at hx
  obtain ⟨β, hβ⟩ := hx
  simp only [add_zero, zero_mul] at hβ
  exact (mul_right_mem_nonZeroDivisors_eq_zero_iff
    (G.familyPow_mem_nonZeroDivisors h β)).mp hβ

end injective

section quotCenter

variable {A : Type (u+1)} [CommRing A] (F : Multicenter A) (T : Ideal A)

/-- The multicenter `{(Mᵢ + T)/T, π(aᵢ)}` induced by `F` on the quotient `A ⧸ T`. -/
def quotCenter : Multicenter (A ⧸ T) where
  index := F.index
  ideal i := Ideal.map (Ideal.Quotient.mk T) (F.ideal i)
  elem i := Ideal.Quotient.mk T (F.elem i)

@[simp] lemma quotCenter_index : (F.quotCenter T).index = F.index := rfl

@[simp] lemma quotCenter_ideal (i : F.index) :
    (F.quotCenter T).ideal i = Ideal.map (Ideal.Quotient.mk T) (F.ideal i) := rfl

@[simp] lemma quotCenter_elem (i : F.index) :
    (F.quotCenter T).elem i = Ideal.Quotient.mk T (F.elem i) := rfl

/-- The `A`-algebra structure on `(A⧸T)[F.quotCenter T]` factors through `A ⧸ T`. -/
lemma algebraMap_quotCenter (x : A) :
    algebraMap A ((A ⧸ T)[F.quotCenter T]) x =
      algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T]) (Ideal.Quotient.mk T x) := rfl

variable (hT : ∀ i, Ideal.Quotient.mk T (F.elem i) ∈ nonZeroDivisors (A ⧸ T))

include hT in
/-- The non-zero-divisor hypothesis for the universal property. -/
lemma quotHom_nzd (i : F.index) :
    algebraMap A ((A ⧸ T)[F.quotCenter T]) (F.elem i) ∈
      nonZeroDivisors ((A ⧸ T)[F.quotCenter T]) := by
  rw [F.algebraMap_quotCenter T]
  exact Dilatation.nonzerodiv_of_nonzerodiv (hT i)

/-- The span hypothesis for the universal property. -/
lemma quotHom_gen (i : F.index) :
    Ideal.span {algebraMap A ((A ⧸ T)[F.quotCenter T]) (F.elem i)} =
      Ideal.map (algebraMap A ((A ⧸ T)[F.quotCenter T])) (F.LargeIdeal i) := by
  refine (gen_iff_le F i).mpr ?_
  have hcomp : (algebraMap A ((A ⧸ T)[F.quotCenter T])) =
      (algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])).comp (Ideal.Quotient.mk T) :=
    RingHom.ext fun x => F.algebraMap_quotCenter T x
  rw [hcomp, ← Ideal.map_map, RingHom.comp_apply]
  exact Multicenter.self_le (F.quotCenter T) i

include hT in
/-- The morphism `φ : A[F] → (A⧸T)[F.quotCenter T]` of the commutative square. -/
noncomputable def quotHom : A[F] →ₐ[A] (A ⧸ T)[F.quotCenter T] :=
  desc F (F.quotHom_nzd T hT) (F.quotHom_gen T)

include hT in
lemma quotHom_frac_spec (ν : F.index →₀ ℕ) (m : F.LargeIdeal ^ ν) :
    algebraMap A ((A ⧸ T)[F.quotCenter T]) (F.elem ^ ν) *
        F.quotHom T hT (m /. ν) =
      algebraMap A ((A ⧸ T)[F.quotCenter T]) (m : A) :=
  dsc_spec F ν m (F.quotHom_nzd T hT) (F.quotHom_gen T)

include hT in
lemma quotHom_elemPow_nzd (ν : F.index →₀ ℕ) :
    algebraMap A ((A ⧸ T)[F.quotCenter T]) (F.elem ^ ν) ∈
      nonZeroDivisors ((A ⧸ T)[F.quotCenter T]) := by
  classical
  simp only [familyPow_def, Finsupp.prod, map_prod, map_pow]
  exact prod_mem fun i _ => pow_mem (F.quotHom_nzd T hT i) _

/-- The large ideals of the quotient multicenter are the images of those of `F`. -/
lemma quotCenter_largeIdeal (i : F.index) :
    (F.quotCenter T).LargeIdeal i =
      Ideal.map (Ideal.Quotient.mk T) (F.LargeIdeal i) := by
  show Ideal.map (Ideal.Quotient.mk T) (F.ideal i) +
      Ideal.span {Ideal.Quotient.mk T (F.elem i)} = _
  rw [LargeIdeal, Submodule.add_eq_sup, Submodule.add_eq_sup, Ideal.map_sup,
    Ideal.map_span, Set.image_singleton]

lemma quotCenter_largeIdealPow (ν : (F.quotCenter T).index →₀ ℕ) :
    (ν.prod fun i k => (F.quotCenter T).LargeIdeal i ^ k) =
      Ideal.map (Ideal.Quotient.mk T) (ν.prod fun i k => F.LargeIdeal i ^ k) := by
  classical
  rw [Finsupp.prod, Finsupp.prod, Ideal.map_finset_prod]
  exact Finset.prod_congr rfl fun i _ => by
    rw [Ideal.map_pow, F.quotCenter_largeIdeal T]

lemma quotCenter_elemPow (ν : (F.quotCenter T).index →₀ ℕ) :
    (ν.prod fun i k => (F.quotCenter T).elem i ^ k) =
      Ideal.Quotient.mk T (ν.prod fun i k => F.elem i ^ k) := by
  classical
  rw [Finsupp.prod, Finsupp.prod, map_prod]
  exact Finset.prod_congr rfl fun i _ => (map_pow _ _ _).symm

include hT in
/-- **`φ` is surjective**: the reduction of a multi-centered dilatation modulo `T` is a
quotient of it.  (For a deformation datum this is the surjectivity of `F_J(i)^*` in
`eq:f_ij-def`.) -/
theorem quotHom_surjective : Function.Surjective (F.quotHom T hT) := by
  intro y
  induction y using Dilatation.induction_on with
  | h pd =>
    obtain ⟨ν, y', hy'⟩ := pd
    have hy'' : y' ∈ Ideal.map (Ideal.Quotient.mk T)
        (ν.prod fun i k => F.LargeIdeal i ^ k) := by
      rw [← F.quotCenter_largeIdealPow T ν]
      exact hy'
    obtain ⟨ℓ, hℓ, hℓy⟩ := (Ideal.mem_map_iff_of_surjective _
      Ideal.Quotient.mk_surjective).mp hy''
    refine ⟨Dilatation.frac (F := F) ν ⟨ℓ, hℓ⟩, ?_⟩
    have hnzd : algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])
        (ν.prod fun i k => (F.quotCenter T).elem i ^ k) ∈
        nonZeroDivisors ((A ⧸ T)[F.quotCenter T]) :=
      Dilatation.nonzerodiv_image (F := F.quotCenter T) ν
    have hlhs : algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])
        (ν.prod fun i k => (F.quotCenter T).elem i ^ k) *
        F.quotHom T hT (Dilatation.frac (F := F) ν ⟨ℓ, hℓ⟩) =
        algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T]) y' := by
      rw [F.quotCenter_elemPow T ν, ← hℓy]
      exact F.quotHom_frac_spec T hT ν ⟨ℓ, hℓ⟩
    have hrhs : algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])
        (ν.prod fun i k => (F.quotCenter T).elem i ^ k) *
        Dilatation.frac (F := F.quotCenter T) ν ⟨y', hy'⟩ =
        algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T]) y' :=
      ((F.quotCenter T).algebraMap_eq_pow_mul_frac ν y' hy').symm
    exact (mul_cancel_left_mem_nonZeroDivisors hnzd).mp (hlhs.trans hrhs.symm)

/-- The ideal `Σ_ν (Lᵛ ∩ T)/aᵛ` of `A[F]`. -/
def kerFracIdeal : Ideal A[F] :=
  Ideal.span {x : A[F] | ∃ (ν : F.index →₀ ℕ) (m : A) (hm : m ∈ F.LargeIdeal ^ ν),
    m ∈ T ∧ x = Dilatation.frac ν ⟨m, hm⟩}

lemma frac_mem_kerFracIdeal (ν : F.index →₀ ℕ) (m : A) (hm : m ∈ F.LargeIdeal ^ ν)
    (hmT : m ∈ T) : Dilatation.frac ν ⟨m, hm⟩ ∈ F.kerFracIdeal T :=
  Ideal.subset_span ⟨ν, m, hm, hmT, rfl⟩

include hT in
/-- **Proposition `propnoyauappendix`** (variant of [Ma24, Prop. 2.39]): the kernel of the
quotient dilatation morphism is the ideal generated by the fractions with numerator in `T`. -/
theorem ker_quotHom :
    RingHom.ker (F.quotHom T hT) = F.kerFracIdeal T := by
  have hinj : Function.Injective
      (algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])) :=
    algebraMap_injective_of_elem_nzd _ hT
  refine le_antisymm ?_ ?_
  · intro x hx
    induction x using Dilatation.induction_on with
    | h pd =>
      obtain ⟨ν, ℓ, hℓ⟩ := pd
      have hx0 : F.quotHom T hT (Dilatation.frac ν ⟨ℓ, hℓ⟩) = 0 := RingHom.mem_ker.mp hx
      have hspec := F.quotHom_frac_spec T hT ν ⟨ℓ, hℓ⟩
      rw [hx0, mul_zero] at hspec
      have h0 : algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])
          (Ideal.Quotient.mk T ℓ) = 0 := hspec.symm
      have hz : Ideal.Quotient.mk T ℓ = 0 := hinj (by rw [map_zero]; exact h0)
      exact F.frac_mem_kerFracIdeal T ν ℓ hℓ (Ideal.Quotient.eq_zero_iff_mem.mp hz)
  · rw [kerFracIdeal, Ideal.span_le]
    rintro x ⟨ν, m, hm, hmT, rfl⟩
    rw [SetLike.mem_coe, RingHom.mem_ker]
    have hspec := F.quotHom_frac_spec T hT ν ⟨m, hm⟩
    have hzero : algebraMap A ((A ⧸ T)[F.quotCenter T])
        ((⟨m, hm⟩ : F.LargeIdeal ^ ν) : A) = 0 := by
      show algebraMap (A ⧸ T) ((A ⧸ T)[F.quotCenter T])
        (Ideal.Quotient.mk T m) = 0
      rw [Ideal.Quotient.eq_zero_iff_mem.mpr hmT, map_zero]
    rw [hzero] at hspec
    exact (mul_left_mem_nonZeroDivisors_eq_zero_iff
      (F.quotHom_elemPow_nzd T hT ν)).mp hspec

end quotCenter

end Multicenter
