import IteratedMultiple
import DilatationCover
import MulticenterSpanEquiv
import PolyptychPanel

/-!
# Deformation data on schemes and their multi-centered deformation spaces

Scheme-level counterpart of `PolyptychDatum`, for Dubouloz-Mayeux, *A polyptych of
multi-centered deformation spaces* (arXiv:2411.15606).

Let `M : PreMultiCenter X` present a family of closed subschemes `Xᵢ` and locally
principal divisors `Dᵢ` on `X`, indexed by a finite totally ordered set `M.indnumb`.
For a subset `J` of the index set, the deformation space

`𝔻_J = Bl^{[Xⱼ , Σ_{s ∈ J≥j} D_s]}_{j ∈ J} X`

is the dilatation of the multicenter `M.defSpace J`, whose divisor attached to `j ∈ J` is
the sum `Σ_{s ∈ J≥j} D_s`, i.e. the *product* of the corresponding ideals on each chart.
Since the covering is unchanged, this is built exactly as `PreMultiCenter.multiple`, via
`ChartDatum`.

Main contents:
* `Ideal.map_finset_prod`, `Ideal.span_singleton_finset_prod` — the two ideal-theoretic
  facts needed to glue the divisor sums and to see that they stay locally principal;
* `defDChartDatum`, `defSpace` — the multicenter `{[Xⱼ, Σ_{s∈J≥j} D_s]}_{j ∈ J}`;
* `defSpace_localMulticenter_ideal`, `defSpace_local_Dideal_span` — the chart-level bridge
  identifying `(M.defSpace J).localMulticenter γ` with the ring-level `restCenter` of
  `PolyptychDatum` (up to the choice of generator, which is only pinned down up to a
  unit, so the bridge is stated as an equality of ideals as elsewhere in this
  development).
-/

suppress_compilation

universe u

open AlgebraicGeometry CategoryTheory Limits TopologicalSpace Multicenter
open Polyptych

section IdealLemmas

variable {A : Type*} [CommRing A]

/-- The ideal generated by a finite product of elements is the product of the ideals they
generate. -/
theorem Ideal.span_singleton_finset_prod {ι : Type*} (S : Finset ι) (g : ι → A) :
    Ideal.span {∏ s ∈ S, g s} = ∏ s ∈ S, Ideal.span {g s} := by
  classical
  induction S using Finset.induction with
  | empty =>
    simp only [Finset.prod_empty, Ideal.one_eq_top]
    exact Ideal.span_singleton_one
  | insert a S ha ih =>
    rw [Finset.prod_insert ha, Finset.prod_insert ha, ← ih,
      Ideal.span_singleton_mul_span_singleton]

end IdealLemmas

namespace SchemeDilatation
namespace PreMultiCenter

variable {X : Scheme.{u+1}} (M : PreMultiCenter X) [LinearOrder M.indnumb]

/-- The chart datum of the divisor sum `Σ_{s ∈ J≥j} D_s`. -/
def defDChartDatum (J : Finset M.indnumb) (j : M.indnumb) : ChartDatum X where
  cov := M.cov
  idl γ := ∏ s ∈ J.filter (fun s => j ≤ s), M.Dideal s γ
  compat a b hab := by
    rw [Ideal.map_finset_prod, Ideal.map_finset_prod]
    exact Finset.prod_congr rfl fun s _ => chartIdeal_agree M.Drep a b hab s

/-- **The deformation space `𝔻_J`** as a multicenter: centers `Xⱼ` for `j ∈ J`, divisors
the sums `Σ_{s ∈ J≥j} D_s`. -/
def defSpace (J : Finset M.indnumb) : PreMultiCenter X where
  indnumb := {j // j ∈ J}
  cov := M.cov
  Ysub j := M.Ysub j.1
  Dsub j := (M.defDChartDatum J j.1).glued
  Yover j := M.Yover j.1
  Dover j := ⟨(M.defDChartDatum J j.1).structureMap⟩
  Yideal j γ := M.Yideal j.1 γ
  Dideal j γ := ∏ s ∈ J.filter (fun s => j.1 ≤ s), M.Dideal s γ
  YcondIso j γ := M.YcondIso j.1 γ
  YcondOver j γ := M.YcondOver j.1 γ
  DcondIso j γ := asIso ((M.defDChartDatum J j.1).chartCompare γ)
  DcondOver j γ := by
    rw [Scheme.Hom.isOver_iff, pullback_over_right, spec_quotient_ideal_over_eq]
    show (M.defDChartDatum J j.1).chartCompare γ ≫
        pullback.snd ((M.defDChartDatum J j.1).structureMap) (M.cov.map γ) =
      Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk
        (∏ s ∈ J.filter (fun s => j.1 ≤ s), M.Dideal s γ)))
    exact (M.defDChartDatum J j.1).chartCompare_snd γ
  Dprin j γ := by
    classical
    refine ⟨⟨∏ s ∈ J.filter (fun s => j.1 ≤ s),
      (M.Dprin s γ).generator, ?_⟩⟩
    · rw [Ideal.submodule_span_eq, Ideal.span_singleton_finset_prod]
      refine Finset.prod_congr rfl fun s _ => ?_
      letI : Submodule.IsPrincipal (M.Dideal s γ) := M.Dprin s γ
      exact (Ideal.span_singleton_generator (M.Dideal s γ)).symm

@[simp] theorem defSpace_Yideal (J : Finset M.indnumb) (j : (M.defSpace J).indnumb)
    (γ : M.cov.J) : (M.defSpace J).Yideal j γ = M.Yideal j.1 γ := rfl

@[simp] theorem defSpace_Dideal (J : Finset M.indnumb) (j : (M.defSpace J).indnumb)
    (γ : M.cov.J) :
    (M.defSpace J).Dideal j γ = ∏ s ∈ J.filter (fun s => j.1 ≤ s), M.Dideal s γ := rfl

@[simp] theorem defSpace_cov (J : Finset M.indnumb) : (M.defSpace J).cov = M.cov := rfl

/-- On a chart, the centers of `𝔻_J` are those of the ring-level `restCenter`. -/
theorem defSpace_localMulticenter_ideal (J : Finset M.indnumb) (γ : M.cov.J)
    (j : (M.defSpace J).indnumb) :
    ((M.defSpace J).localMulticenter γ).ideal j =
      (Polyptych.restCenter (fun i => M.Yideal i γ)
        (fun i => (M.Dprin i γ).generator)
        J).ideal j := rfl

/-- On a chart, the distinguished element of `𝔻_J` at `j` generates the same ideal as the
ring-level `elemOf`, namely `Σ_{s ∈ J≥j} D_s`. -/
theorem defSpace_local_Dideal_span (J : Finset M.indnumb) (γ : M.cov.J)
    (j : (M.defSpace J).indnumb) :
    Ideal.span {((M.defSpace J).localMulticenter γ).elem j} =
      Ideal.span {Polyptych.elemOf
        (fun i => (M.Dprin i γ).generator)
        J j.1} := by
  classical
  letI : Submodule.IsPrincipal ((M.defSpace J).Dideal j γ) := (M.defSpace J).Dprin j γ
  have h1 : Ideal.span {((M.defSpace J).localMulticenter γ).elem j} =
      (M.defSpace J).Dideal j γ :=
    Ideal.span_singleton_generator ((M.defSpace J).Dideal j γ)
  rw [h1, defSpace_Dideal]
  simp only [Polyptych.elemOf]
  rw [Ideal.span_singleton_finset_prod]
  refine Finset.prod_congr rfl fun s _ => ?_
  letI : Submodule.IsPrincipal (M.Dideal s γ) := M.Dprin s γ
  exact (Ideal.span_singleton_generator (M.Dideal s γ)).symm

/-- The ring-level deformation datum read off a chart of `X`. -/
abbrev chartM (γ : M.cov.J) : M.indnumb → Ideal (M.cov.obj γ) := fun i => M.Yideal i γ

/-- The ring-level divisor equations read off a chart of `X`. -/
abbrev chartd (γ : M.cov.J) : M.indnumb → M.cov.obj γ :=
  fun i => (M.Dprin i γ).generator

/-- The chart-level identification `𝔻_J|_γ = Spec R_J`: the two multicenters agree on
ideals and their distinguished elements generate the same ideals. -/
theorem defSpace_chart_agree (J : Finset M.indnumb) (γ : M.cov.J)
    (j : (M.defSpace J).indnumb) :
    ((M.defSpace J).localMulticenter γ).ideal j =
        (Polyptych.restCenter (M.chartM γ) (M.chartd γ) J).ideal j ∧
      Ideal.span {((M.defSpace J).localMulticenter γ).elem j} =
        Ideal.span {(Polyptych.restCenter (M.chartM γ) (M.chartd γ) J).elem j} :=
  ⟨rfl, M.defSpace_local_Dideal_span J γ j⟩

section ChartBridge

variable [Fintype M.indnumb]

/-- **The chart bridge**: on the chart `γ` of `X`, the deformation space `𝔻_J` is exactly
the ring-level `R_J` of `PolyptychDatum`.  The two multicenters have the same centers, and
their distinguished elements generate the same ideals
(`defSpace_local_Dideal_span`), so `Multicenter.spanEquiv` identifies their
dilatations. -/
def chartEquiv (J : Finset M.indnumb) (γ : M.cov.J) :
    Polyptych.Ring (M.chartM γ) (M.chartd γ) J ≃+*
      Multicenter.Dilatation ((M.defSpace J).localMulticenter γ) :=
  (Multicenter.spanEquiv (Polyptych.restCenter (M.chartM γ) (M.chartd γ) J)
    (fun j => ((M.defSpace J).Dprin j γ).generator)
    (fun j => M.defSpace_local_Dideal_span J γ j)).toRingEquiv

@[simp] theorem chartEquiv_algebraMap (J : Finset M.indnumb) (γ : M.cov.J)
    (a : M.cov.obj γ) :
    M.chartEquiv J γ (algebraMap (M.cov.obj γ)
      (Polyptych.Ring (M.chartM γ) (M.chartd γ) J) a) =
      algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) a :=
  (Multicenter.spanEquiv (Polyptych.restCenter (M.chartM γ) (M.chartd γ) J)
    (fun j => ((M.defSpace J).Dprin j γ).generator)
    (fun j => M.defSpace_local_Dideal_span J γ j)).commutes a

/-- **Assumption 3.1 at scheme level**, in chart form: `Xᵢ ∩ D_{i'}` is a Cartier divisor
in `Xᵢ` for all `i, i'`. -/
def CartierDatum : Prop := ∀ γ : M.cov.J, Polyptych.Cartier (M.chartM γ) (M.chartd γ)

/-- The centers of a deformation datum are ordered: `Xᵢ ⊆ X_{i'}` for `i ≥ i'`. -/
def MonoDatum : Prop := ∀ γ : M.cov.J, Polyptych.Mono (M.chartM γ)

/-- **Dilatation-regularity** with respect to `J` (Definition `assutheopan3`), in chart
form. -/
def DilRegular (J : Finset M.indnumb) : Prop :=
  ∀ (γ : M.cov.J) (i : M.indnumb), i ∉ J →
    Polyptych.CondR1 (M.chartM γ) J i ∧
      Polyptych.CondR2 (M.chartM γ) (M.chartd γ) J i

/-- The panel ideal `ker(F_J(i)^*)` read on the chart `γ` of `𝔻_J`. -/
def panelChartIdeal (hC : M.CartierDatum) (J : Finset M.indnumb) (i : M.indnumb)
    (γ : M.cov.J) : Ideal ((M.defSpace J).dilatationCover.obj γ) :=
  Ideal.map (M.chartEquiv J γ).toRingHom
    (RingHom.ker (Polyptych.panelHom (M.chartM γ) (M.chartd γ) (hC γ) J i))

/-- **The kernel formula on the charts of `𝔻_J`** (Proposition `prop:Kernel-formula`
transported through the chart bridge). -/
theorem panelChartIdeal_eq (hC : M.CartierDatum) (hM : M.MonoDatum)
    (J : Finset M.indnumb) (i : M.indnumb) (hiJ : i ∉ J)
    (hreg : M.DilRegular J) (γ : M.cov.J) :
    M.panelChartIdeal hC J i γ =
      Ideal.map (M.chartEquiv J γ).toRingHom
        (Polyptych.panelSubIdeal (M.chartM γ) (M.chartd γ) J i) := by
  rw [panelChartIdeal, Polyptych.ker_panelHom_eq (hC γ) (hM γ) J i hiJ
    (hreg γ i hiJ).1 (hreg γ i hiJ).2]

/-- The panel ideal is the kernel of a surjection out of the chart ring of `𝔻_J`, so it
presents a closed subscheme of that chart (`eq:f_ij-def`). -/
theorem panelChart_surjective (hC : M.CartierDatum) (J : Finset M.indnumb)
    (i : M.indnumb) (γ : M.cov.J) :
    Function.Surjective (fun x => Polyptych.panelHom (M.chartM γ) (M.chartd γ) (hC γ) J i
      ((M.chartEquiv J γ).symm x)) :=
  (Polyptych.panelHom_surjective (M.chartM γ) (M.chartd γ) (hC γ) J i).comp
    (M.chartEquiv J γ).symm.surjective

end ChartBridge

end PreMultiCenter
end SchemeDilatation
