import PolyptychPanelBase

/-!
# The chart comparison for `panelProj : 𝔻_J → 𝔻(panelInt)`

To glue the panel ideals on `𝔻_J` we need the chart-level description of the comparison
morphism `panelProj` of `PolyptychPanelBase`: a ring homomorphism
`panelChartRho : chart_γ(𝔻(panelInt)) ⟶ chart_γ(𝔻_J)` together with the commuting square
`panel_chart_cone`, exactly as `IteratedSchemeMultiCore.proj_chart_cone` does for the
mono-centered projection.  With it, the `ChartDatum.compat` obligation for the panel
ideals on `𝔻_J` is inherited from `chartIdeal_agree` for the globally defined lift of
`Xᵢ` on `𝔻(panelInt)`.
-/

suppress_compilation

universe u

open AlgebraicGeometry CategoryTheory Limits TopologicalSpace Multicenter
open Polyptych

/-- The ideal generated by an image is the extension of the ideal generated. -/
theorem Ideal.span_singleton_map {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (x : R) : Ideal.span {f x} = Ideal.map f (Ideal.span {x}) := by
  rw [Ideal.map_span, Set.image_singleton]

namespace SchemeDilatation
namespace PreMultiCenter

/-- **Cover-free `pullSubset` for schemes over a dilatation**, general form: anything
mapping to `N.dilatation` compatibly over `X` satisfies the containment condition of
`N`. -/
theorem pullSubset_of_over_dilatation' {X : Scheme.{u+1}} (N : PreMultiCenter X)
    {T' : Scheme.{u+1}} (u : T' ⟶ N.dilatation) :
    N.pullSubset (u ≫ N.structureMap) := by
  refine (N.pullSubset_iff (u ≫ N.structureMap)).mpr (fun i γβ => ?_)
  have hcw : ((pull_loc_cov X N.Drep T' (u ≫ N.structureMap) γβ.1).map γβ.2 ≫
        pullback.fst (u ≫ N.structureMap) (N.Drep.cov.map γβ.1) ≫ u) ≫
      N.structureMap =
      Spec.map (pull_mor_ring X N.Drep T' (u ≫ N.structureMap) γβ) ≫
        N.cov.map γβ.1 := by
    rw [spec_map_pull_mor_ring]
    simp only [Category.assoc]
    rw [pullback.condition]
    rfl
  exact N.Yideal_le_Dideal_of_over_dilatation γβ.1 _ _ hcw i

variable {X : Scheme.{u+1}} (M : PreMultiCenter X) [LinearOrder M.indnumb]

/-- The chart of `𝔻_J` is an algebra over the chart of `X` however that base ring is
spelled. -/
instance algPanelIntDefSpace (J : Finset M.indnumb) (i : M.indnumb)
    (γ : M.cov.J) :
    Algebra ((M.panelInt J i).cov.obj γ)
      (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) :=
  inferInstanceAs (Algebra ((M.defSpace J).cov.obj γ)
    (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)))

section ChartNzd

variable (J : Finset M.indnumb) (γ : M.cov.J)

/-- On the chart `γ` of `𝔻_J`, the image of the generator of `𝒟ₛ` is a
non-zero-divisor for every `s ∈ J`. -/
theorem defSpace_chart_gen_nzd (s : M.indnumb) (hs : s ∈ J) :
    algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ))
        ((M.localMulticenter γ).elem s) ∈
      nonZeroDivisors (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) := by
  classical
  have h := nonzerodiv_image_single ((M.defSpace J).localMulticenter γ) ⟨s, hs⟩
  have h0 := congrArg (Ideal.map (algebraMap ((M.defSpace J).cov.obj γ)
      (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) : _ →+* _))
      (M.defSpace_local_Dideal_span J γ ⟨s, hs⟩)
  rw [Ideal.map_span, Set.image_singleton, Ideal.map_span, Set.image_singleton] at h0
  have hprod := nonZeroDivisors_of_span_singleton_eq h0.symm h
  simp only [Polyptych.elemOf, map_prod] at hprod
  have hmem : s ∈ J.filter (fun t => s ≤ t) := Finset.mem_filter.mpr ⟨hs, le_rfl⟩
  rw [← Finset.mul_prod_erase _ _ hmem] at hprod
  exact (mul_mem_nonZeroDivisors.mp hprod).1

/-- On the chart `γ` of `𝔻_J`, the image of `∏_{s ∈ J≥k} d_s` is a
non-zero-divisor. -/
theorem defSpace_chart_prod_nzd (k : M.indnumb) :
    algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ))
        (∏ s ∈ J.filter (fun s => k ≤ s), (M.localMulticenter γ).elem s) ∈
      nonZeroDivisors (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) := by
  classical
  rw [map_prod]
  exact prod_mem fun s hs => M.defSpace_chart_gen_nzd J γ s (Finset.mem_filter.mp hs).1

/-- On the chart `γ` of `𝔻_J`, the divisor ideal of `𝔻_J` at `j ∈ J` extends to the
ideal generated by `∏_{s ∈ J≥j} d_s`. -/
theorem defSpace_chart_self_le (j : M.indnumb) (hj : j ∈ J) :
    Ideal.map (algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)))
        (M.Yideal j γ) ≤
      Ideal.map (algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)))
        (∏ s ∈ J.filter (fun s => j ≤ s), M.Dideal s γ) := by
  refine le_trans (Multicenter.self_le ((M.defSpace J).localMulticenter γ) ⟨j, hj⟩) ?_
  rw [Ideal.span_singleton_map]
  refine Ideal.map_mono (le_of_eq ?_)
  letI : Submodule.IsPrincipal ((M.defSpace J).Dideal ⟨j, hj⟩ γ) :=
    (M.defSpace J).Dprin ⟨j, hj⟩ γ
  exact Ideal.span_singleton_generator _

end ChartNzd

section PanelRho

variable (J : Finset M.indnumb) (i : M.indnumb) (γ : M.cov.J)

/-- The span of the distinguished element of `panelInt` at `k`, on the chart. -/
theorem panelInt_chart_span (k : (M.panelInt J i).indnumb) :
    Ideal.span {((M.panelInt J i).localMulticenter γ).elem k} =
      ∏ s ∈ J.filter (fun s => M.panelKey J i k ≤ s), M.Dideal s γ := by
  letI : Submodule.IsPrincipal ((M.panelInt J i).Dideal k γ) :=
    (M.panelInt J i).Dprin k γ
  have h1 : Ideal.span {((M.panelInt J i).localMulticenter γ).elem k} =
      (M.panelInt J i).Dideal k γ :=
    Ideal.span_singleton_generator ((M.panelInt J i).Dideal k γ)
  rw [h1]
  show (∏ s ∈ J.filter (fun s => M.panelKey J i k ≤ s), M.Dideal s γ) ^ 1 = _
  rw [pow_one]

/-- The non-zero-divisor input for the chart comparison. -/
theorem panelChartRho_nzd (k : (M.panelInt J i).indnumb) :
    algebraMap ((M.panelInt J i).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ))
        (((M.panelInt J i).localMulticenter γ).elem k) ∈
      nonZeroDivisors (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) := by
  classical
  refine nonZeroDivisors_of_span_singleton_eq ?_
    (M.defSpace_chart_prod_nzd J γ (M.panelKey J i k))
  have hgen : Ideal.span {((M.panelInt J i).localMulticenter γ).elem k} =
      Ideal.span {∏ s ∈ J.filter (fun s => M.panelKey J i k ≤ s),
        (M.localMulticenter γ).elem s} := by
    rw [M.panelInt_chart_span J i γ k, Ideal.span_singleton_finset_prod]
    exact Finset.prod_congr rfl fun s _ => M.local_Dideal_span' γ s
  have h0 := congrArg (Ideal.map (algebraMap ((M.defSpace J).cov.obj γ)
    (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)) : _ →+* _)) hgen
  rw [Ideal.map_span, Set.image_singleton, Ideal.map_span, Set.image_singleton] at h0
  exact h0

/-- The containment input for the chart comparison. -/
theorem panelChartRho_gen (hM : M.MonoDatum) (k : (M.panelInt J i).indnumb) :
    Ideal.map (algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ)))
        (M.Yideal (M.panelCtr J i k) γ) ≤
      Ideal.span {algebraMap ((M.defSpace J).cov.obj γ)
        (Multicenter.Dilatation ((M.defSpace J).localMulticenter γ))
        (((M.panelInt J i).localMulticenter γ).elem k)} := by
  classical
  rw [Ideal.span_singleton_map, M.panelInt_chart_span J i γ k]
  cases k with
  | none =>
    by_cases hne : (J.filter (fun s => i ≤ s)).Nonempty
    · obtain ⟨j₀, hj₀J, hij₀, hfil⟩ := M.panelKey_filter_eq J i hne
      have h2 : (∏ s ∈ J.filter (fun s => j₀ ≤ s), M.Dideal s γ) =
          ∏ s ∈ J.filter (fun s => M.panelKey J i none ≤ s), M.Dideal s γ := by
        rw [panelKey_none, hfil]
      rw [← h2]
      exact le_trans (Ideal.map_mono (hM γ hij₀))
        (M.defSpace_chart_self_le J γ j₀ hj₀J)
    · rw [Finset.not_nonempty_iff_eq_empty] at hne
      rw [show J.filter (fun s => M.panelKey J i none ≤ s) = ∅ from hne,
        Finset.prod_empty, Ideal.one_eq_top, Ideal.map_top]
      exact le_top
  | some j =>
    exact le_trans (Ideal.map_mono (hM γ (min_le_right i j.1)))
      (M.defSpace_chart_self_le J γ j.1 j.2)

/-- **The chart comparison ring map** `chart_γ(𝔻(panelInt)) → chart_γ(𝔻_J)`. -/
def panelChartRho (hM : M.MonoDatum) :
    Multicenter.Dilatation ((M.panelInt J i).localMulticenter γ) →ₐ[(M.panelInt J i).cov.obj γ]
      Multicenter.Dilatation ((M.defSpace J).localMulticenter γ) :=
  desc ((M.panelInt J i).localMulticenter γ) (M.panelChartRho_nzd J i γ)
    (fun k => (gen_iff_le ((M.panelInt J i).localMulticenter γ) k).mpr
      (M.panelChartRho_gen J i γ hM k))

/-- The scheme-level chart comparison. -/
def panelRhoSch (hM : M.MonoDatum) :
    (M.defSpace J).chart γ ⟶ (M.panelInt J i).chart γ :=
  Spec.map (CommRingCat.ofHom (M.panelChartRho J i γ hM).toRingHom)

theorem panelRhoSch_chartHom (hM : M.MonoDatum) :
    M.panelRhoSch J i γ hM ≫ (M.panelInt J i).chartHom γ =
      (M.defSpace J).chartHom γ := by
  rw [panelRhoSch]
  show Spec.map _ ≫ Spec.map _ = Spec.map _
  rw [← Spec.map_comp]
  congr 1
  ext a
  exact (M.panelChartRho J i γ hM).commutes a

end PanelRho

section ChartCone

variable (J : Finset M.indnumb) (i : M.indnumb) (hM : M.MonoDatum) (γ : M.cov.J)

include hM in
/-- The chart of `𝔻_J` maps to `X` through the covering, compatibly with
`panelProj`. -/
theorem panelChart_overX :
    ((M.defSpace J).chartTo γ ≫ M.panelProj J i hM) ≫ (M.panelInt J i).structureMap =
      (M.defSpace J).chartToX γ := by
  rw [Category.assoc, M.panelProj_over J i hM, (M.defSpace J).structureMap_chart γ]

/-- The Cartier condition for the chart of `𝔻_J` with respect to `panelInt`. -/
theorem panelChart_isCars :
    IsCars ((M.defSpace J).chart γ)
      (Clos.pullback ((M.defSpace J).chartToX γ) (M.panelInt J i).D) := by
  have heq : (M.defSpace J).chartToX γ =
      (M.defSpace J).chartTo γ ≫ (M.defSpace J).structureMap :=
    ((M.defSpace J).structureMap_chart γ).symm
  rw [heq]
  have hstep : Clos.pullback
      ((M.defSpace J).chartTo γ ≫ (M.defSpace J).structureMap) (M.panelInt J i).D =
      pullback_Clos ((M.defSpace J).chartTo γ)
        (Clos.pullback (M.defSpace J).structureMap (M.panelInt J i).D) := by
    show pullback_Clos _ (Quotient.mk'' (M.panelInt J i).Drep) = _
    rw [pullback_assoc]
    rfl
  rw [hstep]
  haveI : IsOpenImmersion ((M.defSpace J).chartTo γ) :=
    (M.defSpace J).chartTo_isOpenImmersion γ
  haveI : AlgebraicGeometry.Flat ((M.defSpace J).chartTo γ) := inferInstance
  exact pullback_IsCars _ _ _ (M.panelProj_isCars J i)

include hM in
/-- The containment condition for the chart of `𝔻_J` with respect to `panelInt`. -/
theorem panelChart_pullSubset :
    (M.panelInt J i).pullSubset ((M.defSpace J).chartToX γ) := by
  have h := (M.panelInt J i).pullSubset_of_over_dilatation'
    ((M.defSpace J).chartTo γ ≫ M.panelProj J i hM)
  rwa [M.panelChart_overX J i hM γ] at h

include hM in
/-- **The chart cone for `panelProj`**: on charts, the comparison morphism is `Spec` of
the ring-level `panelChartRho`. -/
theorem panel_chart_cone :
    (M.defSpace J).chartTo γ ≫ M.panelProj J i hM =
      M.panelRhoSch J i γ hM ≫ (M.panelInt J i).chartTo γ := by
  refine ((M.panelInt J i).universal_property ((M.defSpace J).chart γ)
    ((M.defSpace J).chartToX γ) (M.panelChart_isCars J i γ)
    (M.panelChart_pullSubset J i hM γ)).unique ?_ ?_
  · exact M.panelChart_overX J i hM γ
  · rw [Category.assoc, (M.panelInt J i).structureMap_chart γ,
      show (M.panelInt J i).chartToX γ =
        (M.panelInt J i).chartHom γ ≫ M.cov.map γ from rfl,
      ← Category.assoc, M.panelRhoSch_chartHom J i γ hM]
    show (M.defSpace J).chartHom γ ≫ M.cov.map γ = _
    rfl

end ChartCone

end PreMultiCenter
end SchemeDilatation
